# Generated by Django 6.0.7 on 2026-08-05 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_patientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='family_medical_history',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='food_preferences',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='food_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='health_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
    ]
