# Generated by Django 6.0.7 on 2026-08-18 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemauditlog_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='plan_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='breakfast',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='dinner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='lunch',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='nutritionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
