# Generated by Django 6.0.7 on 2026-08-27 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dietplan_plan_data_dietplan_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('CLINIC_HOLIDAY', 'Full Clinic Holiday'), ('NUTRITIONIST_LEAVE', 'Nutritionist Leave')], default='CLINIC_HOLIDAY', max_length=30)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
                ('nutritionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'nutritionist', 'holiday_type')},
            },
        ),
    ]
