# Generated by Django 6.0.7 on 2026-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clinicholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
